### ISSUE TITLE
Temperature values not fetched

### ISSUE THREAD

**Issue by km1uk** [mcchots/homebridge-mqtt-temperature#2] opened 2016-10-03 18:37 UTC
I'm having problems getting my temperature readings to show up with Homebridge via MQTT:

> [Living Room Temperature] Living Room Temperature - MQTT :  undefined

I've succesfully managed to subscribe to the appropriate topics on another PC so think the topic should be correct. It also seems to be the same problem on an Ubuntu server and a Pi.

Here is a snippet of my config.json file - does this look correct?

`{`
`"accessory": "mqtt-temperature",`
`"name": "Living Room Temperature",`
`"url": "mqtt://myserver",`
`"topic": "rfm12b/16/2"`
`},`

I'm also using the homebridge-mqtt-humidity version without success. Any hints?

**Comment by mcchots** [comment] 2016-10-05 18:50
Your config looks fine to me. 

Do you have any other homebridge devices that are working? How are you publishing your data values to MQTT.

The only time I get that message is when restarting homebridge and my device has not published a value to mosquitto yet.

Check that your device is actually publishing a value to the topic. You can manually publish some test data as well like this `mosquitto_pub -h myserver -t "rfm12b/16/2" -m "20.2"` assuming you're using `mosquitto`

**Comment by km1uk** [comment] 2016-10-07 08:25
I'm using `homebridge-lightwaverf`, `homebridge-samsungtvcontrol` and `homebridge-tado` succesfully, it's just the MQTT temperature and humidity ones I can't get to work. The data is getting published to MQTT by a node-red workflow (on a different computer to the one running homebridge), and I can see these values if I use an MQTT client on a laptop. I'll check later if I can manually subscribe to the topic on the Pi running homebridge.

I also tried manually publishing as you suggest, but this still didn't work. Maybe re-installing would help? Will  `sudo npm -g uninstall homebridge-mqtt-temperature` work?

**Comment by mcchots** [comment] 2016-10-10 18:48
If you can manually subscribe to the topic on the same device running homebridge, I can't see any reason for the plugins not to work. Do you use authentication for your MQTT server?

**Comment by km1uk** [comment] 2016-10-12 10:29
Running `mosquitto_sub -h myserver -t "rfm12b/16/2"` works (it returns a value to the command line), so I can subscribe to the topic manually, just not via `homebridge-mqtt-temperature`. I'm not using any authentication currently, which is why I removed those lines from config,json. I tried uninstalling and re-installing but have the same issue. Are there any log files that I can look at that might give more clues as to what the issue is?

**Comment by pawkrk** [comment] 2016-10-19 20:15
I have the same problem, I see "MQTT :  undefined". It looks the issue is with MQTT message parsing , to test I publish "22.1" value. It is correct format?

**Comment by mcchots** [comment] 2016-10-25 14:07
At the moment, I can only get this error at times when a value has not been published after homebridge has started or homebridge has the wrong topic. Basically, when communicating with the MQTT server and not getting a valid result. 

The plugin will accept any value either quoted with `"` or without and with a stop `.` as decimal. 
Any of these values should work `22` , `"22"` , `22.1` , `"22.1"`

I will have a look at the mqtt module to see if I can get more debug messages when I get a moment.

**Comment by pawkrk** [comment] 2016-11-12 15:21
I did several tests and added more logging statements. Ive learnt that the issue is not in temperature value format.

Plugin code does not connect correctly to Mosquitto 1.4 or 1.3 servers. It does connect successfully to an old implementation MQTT - RSMB.

**Comment by mcchots** [comment] 2016-11-12 18:30
What versions of Mosquitto and mqtt.js do you have? What version of the plugin do you have?

I currently use `Mosquitto v1.4.10` with `mqtt.js v2.0.1`
I have also tested with `Mosquitto v1.4.9` and `mqtt.js v1.12.0 and v1.14.1` and still cannot reproduce this error.

**Comment by ottopaulsen** [comment] 2016-12-12 21:44
I also have this problem with one of my two sensors. One is reading temperature from an Arduino, the other one from a weather station. Both are sending via the same MQTT (CloudMQTT). Both values are shown up at ThingSpeak.com, and I am also saving both in Firebase and viewing them in an Angular app, but homebridge will only show one of them. I cannot see any formatting error, and the MQTT version should not matter.

Here is my accessory config:
```
  "accessories": [
    {
      "accessory": "mqtt-temperature",
      "name": "Temperatur ute",
      "url": "mqtt://m20.cloudmqtt.com:15555",
      "topic": "weather/outTemp_C",
      "username": "abc",
      "password": "hemmelig"
    },
    {
      "accessory": "mqtt-temperature",
      "name": "Smoky temperatur",
      "url": "mqtt://m20.cloudmqtt.com:15555",
      "topic": "smoky/1/inside/temperature",
      "username": "abc",
      "password": "hemmelig"
    },
    {
      "accessory": "mqtt-humidity",
      "name": "Smoky luftfuktighet",
      "url": "mqtt://m20.cloudmqtt.com:15555",
      "topic": "smoky/1/inside/humidity",
      "username": "abc",
      "password": "hemmelig"
    }
  ],

```

The humidity sensor is also working.

**Comment by ottopaulsen** [comment] 2016-12-13 12:13
Very strange. I wrote the above yesterday, but today it is suddenly showing both temperatures without me doing anything.

**Comment by mcchots** [comment] 2017-02-03 16:04
I'm closing this because I can't replicate on my Pi or PC

**Closed as completed by mcchots** 2017-02-03 16:04 UTC
